### PR TITLE
Add Pre-build Binaries

### LINKED ISSUE #7: Add changelog?
Please add a changelog. It would help when upgrading major versions (e.g. 1.3.2 -> 2.0.10) to check for problems with deprecations etc. in advance.

### LINKED ISSUE #8: Error installing ^2.0.0 with yarn
When I try to install any version > 2.0.0 with yarn on macOS, I get following error:

```
[5/5] 🔨  Building fresh packages...
error /<project-path>/node_modules/node-crc: Command failed.
Exit code: 1
Command: npm run build
Arguments: 
Directory: /<project-path>/node_modules/node-crc
Output:
> node-crc@2.0.10 build
> cargo-cp-artifact -nc index.node -- cargo build --release --message-format=json-render-diagnostics && tsc

Error: could not find the `cargo` executable.

You can find instructions for installing Rust and Cargo at:

    https://www.rust-lang.org/tools/install


Did not copy "cdylib:node-crc"
npm ERR! code 1
npm ERR! path /<project-path>/node_modules/node-crc
npm ERR! command failed
npm ERR! command sh -c cargo-cp-artifact -nc index.node -- cargo build --release --message-format=json-render-diagnostics && tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /<user-path>/.npm/_logs/2021-06-30T13_29_53_039Z-debug.log
```

Find the log-file attached:
[2021-06-30T13_29_53_039Z-debug.log](https://github.com/magiclen/node-crc/files/6741323/2021-06-30T13_29_53_039Z-debug.log)

### LINKED ISSUE #9: Prebuilt binaries to avoid requiring Rust tooling everywhere
Given the change over to using rust, and the lack of rust tooling in most CI infrastructure by default, it might be nice to provide prebuilt binaries. 

There are a few solutions to this, https://github.com/prebuild/prebuildify appears to be one of the most modern solutions to this problem, it includes the prebuilt binaries in the package so no extra downloads needed. https://github.com/prebuild/prebuild-install is an older solution but I've seen it used pretty successfully, artifacts are separate and you use github releases to host them. Since you've already moved to github actions, it should make the configuration pretty simple, if the artifacts end up hosted in the github releases.  I've not looked into if there are any special considerations for doing this with Neon.

If this is interesting to you, I can spend some time trying to make this work and provide a PR within the next 2-3 weeks.

### PR DESCRIPTION
**Pull request by rafaelmaeuer**
Adding prebuilt binaries avoids requiring Rust tooling everywhere.

In the attempt to solve this I played around with [napi-rs](https://github.com/napi-rs/napi-rs) (see [rafaelmaeuer/node-crc/tree/dev/napi](https://github.com/rafaelmaeuer/node-crc/tree/dev/napi)) unless I found out, that cargo already produces the prebuild-binary: `index.node`. 

After learning about the necessity of cross-platform binaries (`invalid ELF header` in Github actions) I ended up writing a [build-script](https://github.com/rafaelmaeuer/node-crc/blob/master/build.sh) based on [cross-rs](https://github.com/cross-rs/cross) and [rustup/cross-compilation](https://rust-lang.github.io/rustup/cross-compilation.html) which can produce [binaries](https://github.com/rafaelmaeuer/node-crc/tree/master/bin) for following platforms (inspired by [sharp](https://github.com/lovell/sharp/blob/main/docs/install.md#cross-platform)):

- macOS x64
- macOS ARM64
- Linux x64 (gnu/musl)
- Linux x86 (gnu/musl)
- Linux ARM64 (gnu/musl)
- Windows x64
- Windows x86

I slightly modified the lib to load the correct binary on each platform and Mocca-Tests are still passing:

```
  CRC-8 Family
    ✔ should calculate CRC-8(CRC-8-ATM)
    ✔ should calculate CRC-8-CDMA

  CRC-16 Family
    ✔ should calculate CRC-16(CRC-16-IBM)
    ✔ should calculate CRC-16-CCITT(CRC-CCITT)

  CRC-24 Family
    ✔ should calculate CRC-24
    ✔ should calculate CRC-24 (using poly)

  CRC-32 Family
    ✔ should calculate CRC-32(CRC-32-IEEE) which is also called crc32b in mhash library
    ✔ should calculate crc32 according to the mhash library
    ✔ should calculate CRC-32-C

  CRC-64 Family
    ✔ should calculate CRC-64(CRC-64-ECMA)
    ✔ should calculate CRC-64-ISO
    ✔ should calculate CRC-64-WE
    ✔ should calculate CRC-64-JONES


  13 passing (9ms)
```

I also created a changelog file from the git history, therefore this PR closes https://github.com/magiclen/node-crc/issues/7, closes https://github.com/magiclen/node-crc/issues/8 and closes https://github.com/magiclen/node-crc/issues/9.

A next step would be to let github-actions produce the binaries and download them from github-artifacts on install.

### CODE REVIEW

**Comment by rafaelmaeuer** [comment]
@magiclen is there any possibility to approve this PR in the nearer future?

**Comment by gemwuu** [comment]
IMHO, these binaries should be published as an external assets, instead of being committed into the repo.

> @magiclen is there any possibility to approve this PR in the nearer future?

**Review by fengmk2 — APPROVED** [review]

**Comment by fengmk2** [comment]
Hope the pr will be merged and release to npm.

**Comment by rafaelmaeuer** [comment]
Today I did some further maintenance on this project, including updates of dependencies and the build-CI. It resulted in an update [v2.1.0](https://github.com/swrlab/node-crc/releases/tag/v2.1.0), feel free to use it until this PR gets merged sometime. @gemwuu we do like the idea of prebuild-binaries being generated in CI and uploaded to release assets, we appreciate any help with https://github.com/swrlab/node-crc/issues/13.

**Pull request closed without merging**
