### PR TITLE
Add support for CRC-64-JONES

### PR DESCRIPTION
**Pull request by daluf**

### CODE REVIEW

**Comment by magiclen** [comment]
Hi, isn't the initial value of CRC-64-JONES `0xFFFFFFFFFFFFFFFF`? In your code, I saw `0x0000000000000000`. I'm not sure about this variant.

**Comment by magiclen** [comment]
Would you write your arguments of the length of bits, expression, reflection, an initial value and a final xor value to `index.d.ts`?

They would be formed into

```
bits = 64, reflection = true, exp = 0x95AC9329AC4BC9B5u64, ini = 0x0000000000000000, fix = 0x0000000000000000
```

**Comment by daluf** [comment]
Added! :)

**Comment by magiclen** [comment]
Thank you!

**Pull request merged**
